android_binary(
    name = "nogotofail",
    custom_package = "net.nogotofail",
    srcs = glob([
        "app/src/main/java/**/.java",
    ]),
    resource_files = glob([
        "app/src/main/res/**/*",
    ]),
    manifest = "app/src/main/AndroidManifest.xml",
)
