android_binary(
    name = "nogotofail",
    custom_package = "net.nogotofail",
    srcs = glob([
        "src/**/*.java",
    ]),
    resource_files = glob([
        "res/**/*",
    ]),
    manifest = "AndroidManifest.xml",
)
